export const DRAFT = 'draft'
export const WAIT_FOR_CUTTING = 'wait_for_cutting'
export const CUTTING_INPROGRESS = 'cutting_inprogress'
export const WAIT_FOR_PREPARING = 'wait_for_preparing'
export const PREPARING_INPROGRESS = 'preparing_inprogress'
export const COMPLETED = 'completed'
export const CANCELLED = 'cancelled'
